---
# tasks file to create docker app_name network

- name: '{{ app_name }} | create network'
  docker_network:
    name:      '{{ app_name }}'
    internal:   "yes"
    state:     'present'

        
