---
gitea_enabled: false
gitea_available_externally: "false"

gitea_docker_image: gitea/gitea:latest

# directories
gitea_data_directory: "{{ docker_home }}/gitea"

# network
gitea_hostname: "gitea"
gitea_port_http: "3001"
gitea_port_ssh: "222"

# specs
gitea_memory: 1g
gitea_mysql_memory: 1g
