---
- name: Create Calibre group
  group:
    name: calibre
    gid: "{{ calibre_group_id }}"
    state: present

- name: Create Calibre user
  user:
    name: calibre
    uid: "{{ calibre_user_id }}"
    state: present
    system: yes
    update_password: on_create
    create_home: no
    group: calibre

- name: Create Calibre-web Directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ calibre_data_directory }}/config"

- name: '{{ app_name }} | network'
  include_tasks: tasks/network.yml

- name: Calibre-web Docker Container
  docker_container:
    name: calibre
    image: "{{ calibre_docker_image }}"
    pull: true
    networks:
      - name: "{{ app_name }}"
    purge_networks: true
    volumes:
      - "{{ calibre_data_directory }}/config:/config"
      - "{{ calibre_books_root }}:/books"
    env:
      TZ: "{{ ansible_nas_timezone }}"
      PUID: "{{ calibre_user_id }}"
      PGID: "{{ calibre_group_id }}"
      DOCKER_MODS: "{{ calibre_ebook_conversion }}"
    restart_policy: unless-stopped
    memory: "{{calibre_memory}}"
    labels:
      traefik.enable: "{{ calibre_available_externally }}"
      traefik.docker.network:                                   "frontend"
      traefik.http.routers.calibre.service:                     "calibre"
      traefik.http.routers.calibre.rule:                        "Host(`{{ calibre_hostname }}.{{ ansible_nas_domain }}`)"
      traefik.http.routers.calibre.tls.certresolver:            "letsencrypt"
      traefik.http.routers.calibre.tls.domains[0].main:         "{{ ansible_nas_domain }}"
      traefik.http.routers.calibre.tls.domains[0].sans:         "*.{{ ansible_nas_domain }}"
      traefik.http.services.calibre.loadbalancer.server.port:   "8083"
      com.centurylinklabs.watchtower.enable:                    "{{ calibre_bitwarden }}"

- name: '{{ app_name }} | network'
  include_tasks: tasks/network_append.yml